### ISSUE TITLE
`import.meta` is used in cjs file

### ISSUE THREAD

**Issue by imranbarbhuiya** [Aslemammad/modern-node-polyfills#11]
My vitest test at https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/actions/runs/4778961061/jobs/8495724668 is failing because of [this](https://github.com/Aslemammad/modern-node-polyfills/blob/84b347ab199367c68258046d1c76c08bd783097c/index.ts#L11) uses `import.meta` in cjs file

**Comment by Aslemammad** [comment]
Please check #12
