### ISSUE TITLE
Add a license 

### ISSUE THREAD

**Issue by imranbarbhuiya** [Aslemammad/modern-node-polyfills#17]
Hi, Thanks for maintaining this awesome library. I was going to use `polyfillPath` (unmodified) and `polyfillContent` ( a bit modified for my use case) functions from this package but as I only needed these functions also needed to modify, so I wasn't installing full deps. But I saw that you don't have any license files in this repo. Can u please add a license here so I can mention that license while using the codes? Thanks again ❤️

**Comment by Aslemammad** [comment]
Sure, why not! Thank you so much.

**Comment by Aslemammad** [comment]
done!
