### ISSUE TITLE
CJS build contains import.meta

### ISSUE THREAD

**Issue by TheNoim** [Aslemammad/modern-node-polyfills#5]
index.cjs contains a reference to import.meta which breaks the cjs file.

![image](https://user-images.githubusercontent.com/5133056/211004377-79c6ebea-8b89-4ca3-abe0-9954d9026a04.png)

And another note: It would be helpful to have the https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository field filled with this repo. Because at the moment [npmjs.com](https://www.npmjs.com/package/modern-node-polyfills) doesn't know what the source repo is. This makes it hard to find it.

**Comment by Aslemammad** [comment]
Oh Nice, thank u so much! Do you want to work on the first or the second part?

**Comment by Aslemammad** [comment]
@TheNoim Hey, I've been able to fix this, please check if it works.
