### ISSUE TITLE
Failed to polyfill `fs/promises`

### ISSUE THREAD

**Issue by christian-bromann** [Aslemammad/modern-node-polyfills#6]
Calling `polyfillPath` with `fs/promises` fails due to this line:

```ts
  const jspmPath = resolve(
    require.resolve(`@jspm/core/nodelibs/${module}`),
    "../../.."
  );
```

I'ld suggest maybe this workaround:

```ts
  const jspmPath = resolve(
    require.resolve(`@jspm/core/nodelibs/${module}`),
    "../../.." + (module.includes('/') ? "/.." : "")
  );
```

Happy to make a PR if we agree on a resolution.

**Comment by Aslemammad** [comment]
If it passes the tests, feel free to!

**Comment by christian-bromann** [comment]
@Aslemammad raised a PR, please approve it to run so we can see if test pass.
